export { default as Hero } from './HeroPage.vue'
export { default as IcanBusines } from './IcanBusines.vue'
export { default as IcanChoose } from './IcanChoose.vue'
export { default as NewPage } from './NewPage.vue'
export { default as Partner } from './PartnerPage.vue'
export { default as MapsPage } from './MapsPage.vue'
export { default as Footer } from './FooterPage.vue'
export { default as Home } from './HomePage.vue'
